version: "3.8"
services:
  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
